# Generated by Django 5.1 on 2024-09-23 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_moonphaseeventpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantBeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Número dos canteiros, ex: 1,2 ou 1-3', max_length=255, null=True)),
                ('bed_number', models.IntegerField()),
                ('current_planted_seed', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='moonphase',
            name='date',
        ),
        migrations.AddField(
            model_name='moonphase',
            name='phase_hawaii',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CyclicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('beds', models.CharField(help_text='Número dos canteiros, ex: 1,2 ou 1-3', max_length=255)),
                ('frequency', models.CharField(choices=[('weekly', 'Semanal'), ('biweekly', 'A cada duas semanas'), ('monthly', 'Mensal'), ('2.5months', 'A cada 2.5 meses'), ('4months', 'A cada 4 meses')], max_length=50)),
                ('start_date', models.DateField()),
                ('calendar_color', models.CharField(max_length=7)),
                ('moon_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.moonphase')),
            ],
        ),
        migrations.CreateModel(
            name='MoonPhaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('moon_phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.moonphase')),
            ],
        ),
    ]
