# Generated by Django 5.1 on 2024-09-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_plantbeds_remove_moonphase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moonphase',
            name='calendar_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='cyclicevent',
            name='calendar_color',
            field=models.CharField(blank=True, default='#000000', max_length=7, null=True),
        ),
    ]
