# Generated by Django 5.1 on 2024-09-24 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_moonphase_calendar_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moonphaseevent',
            name='date',
        ),
        migrations.AddField(
            model_name='moonphaseevent',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 1, 18, 26, 687181, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
