# Generated by Django 5.1 on 2024-10-11 14:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_cyclicevent_beds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=1000)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CyclicEventPage',
            fields=[
                ('eventpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.eventpage')),
                ('completed', models.BooleanField()),
                ('cyclic_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.cyclicevent', verbose_name='Cyclic event')),
            ],
            options={
                'verbose_name': 'CodeRed Event',
                'abstract': False,
            },
            bases=('website.eventpage',),
        ),
    ]
