# Generated by Django 5.1 on 2024-10-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_note_cycliceventpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycliceventpage',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
