# Generated by Django 5.1 on 2024-10-29 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_cycliceventpage_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da semente, ex: Rosa, Gardênia', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='plantbeds',
            name='current_planted_seed',
        ),
        migrations.CreateModel(
            name='Plantation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('plant_bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantations', to='website.plantbeds')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantations', to='website.seed')),
            ],
        ),
    ]
