# Generated by Django 5.1 on 2024-10-29 16:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0041_remove_layoutsettings_frontend_theme'),
        ('website', '0011_seed_remove_plantbeds_current_planted_seed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantBedListPage',
            fields=[
                ('coderedpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coderedcms.coderedpage')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('coderedcms.coderedpage',),
        ),
        migrations.CreateModel(
            name='PlantBedPage',
            fields=[
                ('coderedpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coderedcms.coderedpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('coderedcms.coderedpage',),
        ),
    ]
