# Generated by Django 5.1 on 2024-10-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_plantbedlistpage_plantbedpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantBedPage',
        ),
    ]
