# Generated by Django 5.1 on 2024-11-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_eventpage_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seed',
            new_name='Plant',
        ),
    ]
